### ISSUE TITLE
Error Kali Linux.

### ISSUE THREAD

**Issue by gabilette** [omergunal/hackerbot#2]
Dear:
When running hackerbot.py in kali linux with python 2.7.13 I receive the error:

File "hackerboy.py", line 8
SintaxError: Non-ASCII character '\xc3' in file hackerbot.py on line 8, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details.

did you know why i get this error?
regards.-

**Comment by omergunal** [comment]
i fixed it, can you download again?
thanks for feedback.

**Comment by gabilette** [comment]
Thanks! it works, but y get another error.

**Comment by omergunal** [comment]
Can you write the error?

**Comment by 8aplus** [comment]
I think he got this (Kali 2017.2)

Traceback (most recent call last):
File "modules/tweets_analyzer.py", line 22, in <module>
from ascii_graph import Pyasciigraph
ImportError: No module named 'ascii_graph'

**Comment by omergunal** [comment]
@8aplus can you try "pip install ascii_graph". if you havent pip, you should install pip first.(https://pip.pypa.io/en/stable/installing/)

**Comment by 8aplus** [comment]
Thx but it is already installed.

pip install ascii_graph
Requirement already satisfied: ascii_graph in /usr/local/lib/python2.7/dist-packages

**Comment by omergunal** [comment]
@8aplus can you try this:

- pip uninstall ascii_graph
- pip install ascii_graph

**Comment by 8aplus** [comment]
I tried it but it got the same error message.

**Comment by omergunal** [comment]
@8aplus  please redownload this tool and try again.I changed something

**Comment by cegi** [comment]
Hi, i have the same problem, the error still persist. On Kali-Linux 2017.3

Traceback (most recent call last):
File "modules/tweets_analyzer.py", line 22, in
from ascii_graph import Pyasciigraph
ImportError: No module named 'ascii_graph'

For the rest, it works, thanks for the tool.

**Comment by omergunal** [comment]
@cegi hi, did you try this: pip install ascii_graph

**Comment by issyilly** [comment]
I'm having a problem opening it in termux

**Comment by issyilly** [comment]
Can you give me cmd prompt in order of what to do it show this Traceback (most recent call last):
  File "hackerbot.py", line 2, in <module>
    import aiml
ImportError: No module named aiml I try to open

**Comment by omergunal** [comment]
@issyilly You should install aiml, can you try  this: "pip2 install -r requirements.txt"  or "sudo apt-get install python-aiml"

**Comment by Obasoro** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!degan, @saitejakuruva, @ljmiao, @nkmajeti, @ido, @lxhelili, @bunlusarac, @Nitori111, @william-zxs, @nadongjun, @evenluo, @bugparty, @0xbeny, @bhalla98, @copmoa, @saturnial, @flyingcherry, @dinadeljanin, @obernardovieira, @FuYung

**Comment by duskagain** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!fafifox, @david-dacruz, @philippnagel, @discountry, @houjingyi233, @mediter, @cz35iek, @skmonga, @ghanem-mhd, @omotcha, @joshualouden, @JustCallMeAD, @JustDravee, @jyterencekim, @simonbennet, @kuri0sity, @Methimpact, @edwinyung, @egreaves, @danBamikiya
